name: Watch External Release

on:
  schedule:
    - cron: '0 */6 * * *'  # Check every 6 hours

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/sindresorhus/github-markdown-css/releases/latest)
          latest_tag=$(echo $latest_release | jq -r .tag_name)
          current_tag=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name || echo "none")
          if [ "$latest_tag" != "$current_tag" ]; then
            curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"event_type":"github-markdown-css-release"}'
